sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    # coveralls is not listed in tox's envlist, but should run in travis
    - TESTENV=coveralls
    # note: please use "tox --listenvs" to populate the build matrix below
    - TESTENV=linting
    - TESTENV=py26
    - TESTENV=py27
    - TESTENV=py33
    - TESTENV=py34
    - TESTENV=py35
    - TESTENV=pypy
    - TESTENV=py27-pexpect
    - TESTENV=py27-xdist
    - TESTENV=py27-trial
    - TESTENV=py35-pexpect
    - TESTENV=py35-xdist
    - TESTENV=py35-trial
    - TESTENV=py27-nobyte
    - TESTENV=doctesting
    - TESTENV=freeze
    - TESTENV=docs

matrix:
  allow_failures:
    # py35-trial failing on Linux: #1989
    - env: TESTENV=py35-trial
  include:
    - env: TESTENV=py36
      python: '3.6-dev'

script: tox --recreate -e $TESTENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
