sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    # coveralls is not listed in tox's envlist, but should run in travis
    - TOXENV=coveralls
    # note: please use "tox --listenvs" to populate the build matrix below
    - TOXENV=linting
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py27-pexpect
    - TOXENV=py27-xdist
    - TOXENV=py27-trial
    - TOXENV=py27-numpy
    - TOXENV=py27-pluggymaster
    - TOXENV=py35-pexpect
    - TOXENV=py35-xdist
    - TOXENV=py35-trial
    - TOXENV=py35-numpy
    - TOXENV=py35-pluggymaster
    - TOXENV=py27-nobyte
    - TOXENV=doctesting
    - TOXENV=freeze
    - TOXENV=docs

matrix:
  include:
    - env: TOXENV=py26
      python: '2.6'
    - env: TOXENV=py33
      python: '3.3'
    - env: TOXENV=pypy
      python: 'pypy-5.4'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=py37
      python: 'nightly'
  allow_failures:
    - env: TOXENV=py37
      python: 'nightly'

script: tox --recreate

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
