sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    - TESTENV=coveralls
    - TESTENV=doctesting
    - TESTENV=linting
    - TESTENV=py26
    - TESTENV=py27
    - TESTENV=py27-cxfreeze
    - TESTENV=py27-nobyte
    - TESTENV=py27-pexpect
    - TESTENV=py27-subprocess
    - TESTENV=py27-trial
    - TESTENV=py27-xdist
    - TESTENV=py33
    - TESTENV=py33
    - TESTENV=py34
    - TESTENV=py35-pexpect
    - TESTENV=py35-trial
    - TESTENV=py35-xdist
    - TESTENV=py35
    - TESTENV=pypy

script: tox --recreate -e $TESTENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
