name: prepare release pr

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to base the release from'
        required: true
        default: ''
      major:
        description: 'Major release? (yes/no)'
        required: true
        default: 'no'
      prerelease:
        description: 'Prerelease (ex: rc1). Leave empty if not a pre-release.'
        required: false
        default: ''

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        # persist-credentials is needed in order for us to push the release branch.
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.13"

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-uv

    - name: Prepare release PR (minor/patch release)
      if: github.event.inputs.major == 'no'
      env:
        BRANCH: ${{ github.event.inputs.branch }}
        PRERELEASE: ${{ github.event.inputs.prerelease }}
        GH_TOKEN: ${{ github.token }}
      run: |
        tox -e prepare-release-pr -- "$BRANCH" --prerelease="$PRERELEASE"

    - name: Prepare release PR (major release)
      if: github.event.inputs.major == 'yes'
      env:
        BRANCH: ${{ github.event.inputs.branch }}
        PRERELEASE: ${{ github.event.inputs.prerelease }}
        GH_TOKEN: ${{ github.token }}
      run: |
        tox -e prepare-release-pr -- "$BRANCH" --major --prerelease="$PRERELEASE"
