name: prepare release pr

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to base the release from'
        required: true
        default: ''
      major:
        description: 'Major release? (yes/no)'
        required: true
        default: 'no'
      prerelease:
        description: 'Prerelease (ex: rc1). Leave empty if not a pre-release.'
        required: false
        default: ''

# Set permissions at the job level.
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
        # persist-credentials is needed in order for us to push the release branch.
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.13"

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-uv

    - name: Prepare release PR (minor/patch release)
      if: github.event.inputs.major == 'no'
      env:
        BRANCH: ${{ github.event.inputs.branch }}
        PRERELEASE: ${{ github.event.inputs.prerelease }}
        GH_TOKEN: ${{ github.token }}
      run: |
        tox -e prepare-release-pr -- "$BRANCH" --prerelease="$PRERELEASE"

    - name: Prepare release PR (major release)
      if: github.event.inputs.major == 'yes'
      env:
        BRANCH: ${{ github.event.inputs.branch }}
        PRERELEASE: ${{ github.event.inputs.prerelease }}
        GH_TOKEN: ${{ github.token }}
      run: |
        tox -e prepare-release-pr -- "$BRANCH" --major --prerelease="$PRERELEASE"
