name: Update Plugin List

on:
  schedule:
    # At 00:00 on Sunday.
    # https://crontab.guru
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Set permissions at the job level.
permissions: {}

jobs:
  update-plugin-list:
    if: github.repository_owner == 'pytest-dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.13"

      - name: requests-cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.cache/pytest-plugin-list/
          key: plugins-http-cache-${{ github.run_id }} # Can use time based key as well
          restore-keys: plugins-http-cache-

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Update Plugin List
        run: tox -e update-plugin-list

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725
        with:
          commit-message: '[automated] Update plugin list'
          author: 'pytest bot <pytestbot@users.noreply.github.com>'
          branch: update-plugin-list/patch
          delete-branch: true
          branch-suffix: short-commit-hash
          title: '[automated] Update plugin list'
          body: '[automated] Update plugin list'
          draft: true

      - name: Instruct the maintainers to trigger CI by undrafting the PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PULL_REQUEST_NUMBER: ${{ steps.pr.outputs.pull-request-number }}
        run: >-
          gh pr comment
          --body 'Please mark the PR as ready for review to trigger PR checks.'
          --repo '${{ github.repository }}'
          "$PULL_REQUEST_NUMBER"
